---
title: "Lab 4: Tidying your dataset"
author: "Karena Andrea Moreno-Acero"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    highlight: tango
    toc: false
    df_print: kable
    fig_caption: no
    number_sections: no
    dev: pdf
  html_document:
    highlight: tango
    self_contained: true
    theme: paper
    toc: no
    df_print: kable
    fig_caption: no
    number_sections: no
    smart: yes
    dev: svg
  github_document:
    html_preview: false
    toc: true
    toc_depth: 4
    dev: svg
    df_print: kable
---

```{r setup, include = FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# Set knitr options
knitr::opts_chunk$set(
  echo = TRUE, eval = TRUE, fig.width = 5,
  fig.asp = 0.618, out.width = "80%", dpi = 120,
  fig.align = "center", cache = FALSE
)

# Load packages
suppressPackageStartupMessages(library(tidyverse))

# Load dataset
brauer <- read_rds("brauer2008.rds")
```

------------------------------------------------------------------------

## Prune the dataset


### Exercise 1

## Enforcing one observation per row
```{r}
brauer2 <- brauer %>% select(-GID, -YORF, -GWEIGHT)
```

### Exercise 2
```{r}
brauer3 <- brauer2 %>% 
  pivot_longer(
    cols = G0.05:U0.3, 
    names_to = "sample", 
    values_to = "expression", 
    values_drop_na = TRUE
    )
```


## Enforcing one column per variable and one value per cell

### Exercise 3

```{r}
brauer4 <- brauer3 %>%
  separate(
    col = sample,
    into = combine("nutrient", "rate"),
    sep = 1
  )
```

### Exercise 4
```{r}
brauer5 <- brauer4 %>%
  separate(
    col = NAME,
    into = combine("gene_name", "biological_process","molecular_function", "systematic_id", "number"),
    sep =  "\\|\\|"
  )
```

### Exercise 5
```{r}
brauer_tidy<- brauer5 %>%
  mutate_at(vars(gene_name:systematic_id), str_trim)
```



## Visualizations using the tidy dataset

### Exercise 6
```{r}
brauer_tidy %>% filter(gene_name == "LEU1") %>%
  ggplot()+
  geom_line(aes(x=rate,y=expression, group = nutrient, color= nutrient ))
```

